service: habit-tracker

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1
  httpApi:
    cors:
      allowedOrigins:
        - https://habit-tracker-two-virid.vercel.app   # prod-frontend
        - http://localhost:3000                        # dev-frontend
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowedHeaders:
        - Content-Type
      allowCredentials: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Habits

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  

functions:
  api:
    handler: app.main.handler     # app/main.py  →  handler = Mangum(app)
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
